### PR TITLE
Hello world example

### PR DESCRIPTION
**Pull request by Cengkaruk**
Just write hello-world example :)

### CODE REVIEW

**Comment by mdamt** [comment]
Pak @herpiko, could you please help reviewing this? Thanks.

**Comment by herpiko** [comment]
It seems good. But how about involve some line of javascript. Since Maleo is a "HTML5" wrapper, this should provide an example how to play with javascript too. I am thinking about a button that shouting "Hello world!" when clicked.

**Comment by adzymaniac** [comment]
Thanks @herpiko 
I will include some line of javascript. After this request merged, i will request again for another example using nodejs.

*salim*

**Comment by herpiko** [comment]
Thank you Pak De @adzymaniac !

**Pull request merged**
